### ISSUE TITLE
Change licence in package.json

### ISSUE THREAD

**Issue by CalaoJuanPablo** [swat-hopper/hopper-frontend#45]
Add "Apache-2.0" to the license in `package.json` file

**Comment by jdrios-dev** [comment]
Changes on Front and Backend repo License done

**Comment by CalaoJuanPablo** [comment]
Ok. Cool. The idea is to create a new branch for each task/issue, and then submit a PR with the solution. Take that into account for the next time. I will prepare documentation for the git and GitHub workflow
